[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[nixpacks]
node_version = "22"

[deploy]
startCommand = "npm run start:http"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
internalPort = 3001
